### ISSUE TITLE
Zemismart Zigbee Blind

### ISSUE THREAD

**Issue by jorgespneto** [Mark-C-uk/Hubitat#2]
Hi Mark, 
Only the curtain opening command is working, the curtain closing command is not working

**Comment by robohofo** [comment]
I had the same issue and after reading (and re-re-reading) [this thread](https://community.hubitat.com/t/tuya-zigbee-roller-shade-port-help/43783), it became clear that you need to use the included remote and following the ZeniSmart instructions for setting the upper and lower limit for the blinds. Then it will start to work.

**Comment by Mark-C-uk** [comment]
this driver is for tube motors not chain motors
